### ISSUE TITLE
Runtime Error when closing launcher

### ISSUE THREAD

**Issue by skipster1337** [AfoninZ/UltimMC#152]
### Operating System

Windows

### Description of bug

Closing the launcher leads to a Runtime Error:
"This application has requested the Runtime to terminate it in an unusual way. Please contact the application's support team for more information."

I am running Windows 10, and have the Visual C++ Runtimes installed. The crash seems to happen on multiple computers of mine.

### Steps to reproduce

Close the launcher by clicking on the close button in the title bar.

### Suspected cause

The bug is related to the Visual C++ Runtime

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Sebastian-byte** [comment]
I'm unable to reproduce, likely fixed in newer versions of the launcher.

**Comment by skipster1337** [comment]
I still get this error on the latest version of the launcher.
![2022-12-04 18_39_46-Microsoft Visual C++ Runtime Library](https://user-images.githubusercontent.com/91155070/205503818-14189665-df53-4732-9d19-cc19648da61d.png)
![2022-12-04 18_41_28-A Minecraft Launcher](https://user-images.githubusercontent.com/91155070/205503820-ef8e6582-1712-4d55-bc6a-cff8b106ef30.png)  
The error details read:
```Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	UltimMC.exe
  Application Version:	1.0.0.0
  Application Timestamp:	057dcfe0
  Fault Module Name:	libstdc++-6.dll
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	00000000
  Exception Code:	40000015
  Exception Offset:	0001f11d
  OS Version:	6.3.9600.2.0.0.256.89
  Locale ID:	2057
  Additional Information 1:	c80a
  Additional Information 2:	c80a69c0c8acc0459017deae2eb1510a
  Additional Information 3:	c002
  Additional Information 4:	c002c3efab5bc6f19e7628e32a300cc3

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=280262

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt
